### ISSUE TITLE
version 1.1 does not work on windows 10 and windows server 2012 r2

### ISSUE THREAD

**Issue by yoke88** [lallousx86/WEPExplorer#1]
It can list all the provider with no problem,but when list provider metadata or list provider event metadata, the xml can not write complete.

`PS C:\Users\yoke88\Desktop\WEPExplore_v1.0\Tools> .\cli.exe /name  Microsoft-Windows-Security-Auditing /eventmeta /ou
t e:\aa.xml`

I changed the name of aa.xml to aa.txt and you can see it below

[aa.txt](https://github.com/lallousx86/WEPExplorer/files/173166/aa.txt)

`

**Comment by yoke88** [comment]
The main purpose i want use this tool is because when i using wevtutil.exe or powershell to event metadata of provider microsoft-windows-security-auditing ,the task field always equal 0

here is the powershell i used:

<code>$ProviderMetadataList = New-Object -TypeName System.Diagnostics.Eventing.Reader.ProviderMetadata -ArgumentList Microsoft-Windows-Security-Auditing`

![default](https://cloud.githubusercontent.com/assets/3146226/13766329/df765866-ea9b-11e5-8cf0-e1a3b31d1afb.PNG)

can your tools show the value of  task field  of event metadata of microsoft-windows-security-auditing provider?

**Comment by lallousx86** [comment]
Thanks for reporting. Fixed. Please get the new version 1.1.1.
Make sure you do "File / Clear cache" afterwards.
